### ISSUE TITLE
Cannot install from APT debian repository

### ISSUE THREAD

**Issue by Na0mir** [jesec/rtorrent#21] opened 2021-09-13 09:36 UTC
Hello~

I'm trying to install rtorrent from your Debian repository but having issues:
(from flood installation link: https://github.com/jesec/flood/wiki/Install-Flood-on-Debian,-Ubuntu-and-derivatives)

```
root@flood:~# sudo apt install -y rtorrent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rtorrent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2143 kB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://deb.jesec.io devel/main amd64 rtorrent amd64 0.9.8-jc+1622031270-f8537e3
  Connection failed [IP: 104.21.51.24 443]
E: Failed to fetch https://decompressor.jesec.workers.dev/?decompress=https://nightly.link/jesec/rtorrent/actions/runs/878467218/rtorrent-deb-amd64.zip  Connection failed [IP: 104.21.51.24 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
![image](https://user-images.githubusercontent.com/6453724/133060834-6c245321-6bd2-43be-9a9b-dce147706132.png)
For unknown reasons artifact 878467218 returns to 6453724 which seems expired 🤔
Thank you! Keep going on your awesome work ❤

**Comment by jesec** [comment] 2021-10-08 03:35
The issue is resolved by https://github.com/jesec/deb.jesec.io/commit/0849482d9ab64ad24298a210b29387081fbdc109. 

Feel free to close it.

**Closed** 2021-10-08 06:47 UTC
